name: build

on:
  pull_request:
    types: [opened]

jobs:
  version_comment:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Add PR Comment
        id: add_pr_comment
        uses: octokit/request-action@v2.x
        with:
          route:
            POST /repos/${{ github.repository }}/issues/${{
            github.event.pull_request.number }}/comments
          body: '"Change me to the comment you want to automatically put 🐶"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
